[package]
name = "manager"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
config = "0.14.0"
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
