[meta]
id = "worker-1"

[nats]
host = "demo.nats.io"
topic = "bmonikraj-rs-distributed-compute-task"

[mongodb]
cnx = "mongodb+srv://bmonikraj:IfxTUalmQ6uONiU7@cluster0.yqupv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"