[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
mongodb = { version = "3.1.0", features = ["sync"] }
